### ISSUE TITLE
Overview

### ISSUE THREAD

**Issue by ljgarcia** [biojs-edu/vizbi-exercise1#1]
Hi there, 

Looking good!
Some overview about what this exercise is about, at the very beginning, could be missing. An overview would give an idea about what to expect from this exercise, something like learning objectives maybe.

**Comment by wilzbach** [comment]
Hi Leyla,

> Looking good!

Thanks :)

> Some overview about what this exercise is about, at the very beginning, could be missing. An overview would give an idea about what to expect from this exercise, something like learning objectives maybe.

I added two slides at the beginning (overview + sneak) - thanks again for the idea.
BTW at the moment this is part of http://vizbi.biojs.net/program/
